const talitas = [
  {
    id: 0,
    sabor: "Canela y Azúcar",
    imagen: "imagenes/talita.webp",
    precio: 300,
    cantidad: 0,
    tipo: "dulces",
    descripcion: "Con canela y granos de azúcar",
    precioAcumulado: 300,
  },
  {
    id: 1,
    sabor: "Azúcar",
    imagen: "imagenes/talita.webp",
    precio: 300,
    cantidad: 0,
    tipo: "dulces",
    descripcion: "Con granos de azúcar",
    precioAcumulado: 300,
  },
  {
    id: 2,
    sabor: "Original",
    imagen: "imagenes/talita.webp",
    precio: 600,
    cantidad: 0,
    tipo: "sin_sal",
    descripcion: "Toda la originalidad de Donatto",
    precioAcumulado: 600,
  },
  {
    id: 3,
    sabor: "Jamón",
    imagen: "imagenes/talita.webp",
    precio: 600,
    cantidad: 0,
    descripcion: "Intenso sabor a jamón",
    precioAcumulado: 600,
  },
  {
    id: 4,
    sabor: "Queso",
    imagen: "imagenes/talita.webp",
    precio: 600,
    cantidad: 0,
    descripcion: "Intenso sabor a queso, con queso rayado encima",
    precioAcumulado: 600,
  },
  {
    id: 5,
    sabor: "Cebolla",
    imagen: "imagenes/talita.webp",
    precio: 600,
    cantidad: 0,
    descripcion: "Intenso sabor a cebolla, con pedazos de cebolla",
    precioAcumulado: 600,
  },
  {
    id: 6,
    sabor: "Orégano",
    imagen: "imagenes/talita.webp",
    precio: 600,
    cantidad: 0,
    descripcion: "Intenso sabor a orégano",
    precioAcumulado: 600,
  },
  {
    id: 7,
    sabor: "Pizza",
    imagen: "imagenes/talita.webp",
    precio: 600,
    cantidad: 0,
    descripcion: "Intenso sabor a pizza",
    precioAcumulado: 600,
  },
  {
    id: 8,
    sabor: "Mix de Semillas",
    imagen: "imagenes/talita.webp",
    precio: 600,
    cantidad: 0,
    tipo: "sin_sal",
    descripcion: "Con semillas de lino, chía y salvado",
    precioAcumulado: 600,
  },
  {
    id: 9,
    sabor: "Espinaca",
    imagen: "imagenes/talita.webp",
    precio: 600,
    cantidad: 0,
    tipo: "verdura",
    descripcion: "Intenso sabor a espinaca",
    precioAcumulado: 600,
  },
  {
    id: 10,
    sabor: "Calabaza",
    imagen: "imagenes/talita.webp",
    precio: 600,
    cantidad: 0,
    tipo: "verdura",
    descripcion: "Intenso sabor a calabaza",
    precioAcumulado: 600,
  },
  {
    id: 11,
    sabor: "Chía",
    imagen: "imagenes/talita.webp",
    precio: 600,
    cantidad: 0,
    descripcion: "Con semillas de chía",
    precioAcumulado: 600,
  },
  {
    id: 12,
    sabor: "Lino",
    imagen: "imagenes/talita.webp",
    precio: 600,
    cantidad: 0,
    descripcion: "Con semillas de lino",
    precioAcumulado: 600,
  },
  {
    id: 13,
    sabor: "Sésamo",
    imagen: "imagenes/talita.webp",
    precio: 600,
    cantidad: 0,
    descripcion: "Con semillas de sésamo",
    precioAcumulado: 600,
  },
  {
    id: 14,
    sabor: "Salvado",
    imagen: "imagenes/talita.webp",
    precio: 600,
    cantidad: 0,
    tipo: "sin_sal",
    descripcion: "Con semillas de salvado",
    precioAcumulado: 600,
  },
];

guardarProducto();
